version: '3.1'
services:
  stats-server:
    build: stat-service/server
    container_name: stat-server-container
    ports:
      - "8080:8080"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:13
    container_name: stat-db-container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root